
LLM = "gpt"
#LLM = "huggingface"
#LLM = "llamacpp"
GPT_MODEL = "gpt-4o-mini"
#GPT_MODEL = "gpt-3.5-turbo"
#GPT_MODEL = "gpt-3.5-turbo-0125"
#GPT_MODEL = "gpt-3.5-turbo-1106"
#GPT_MODEL = "gpt-3.5-turbo-instruct"
#GPT_MODEL = "gpt-4"
#GPT_MODEL = "gpt-4o"
GPT4O_MODEL = "gpt-4o"
#GPT_MODEL = "gpt-4o-mini"
#GPT_MODEL = "gpt-4o-2024-08-06"
OLLAMA_MODEL = "llama3.1"
HF_MODEL = "HuggingFaceH4/zephyr-7b-beta"
CPP_MODEL = "mistralai/Mistral-7B-Instruct-v0.2"
#EMBED_MODEL = "local"
#EMBED_MODEL = "text-embedding-ada-002"
#EMBED_MODEL = "text-embedding-3-small"
#EMBED_MODEL = "text-embedding-3-large"
EMBED_MODEL = "local:BAAI/bge-small-en-v1.5"
MODE = "query"
#kMODE = "chat"
#MODE = "agent"

config = {"configurable": {"session_id": "ses1"}}